name: influencer_Search

on:
  push:
  schedule:
    - cron: "0 1 1,15 * *"

permissions:
  contents: write

jobs:
  run-influencer-search:
    runs-on: ubuntu-latest

    env:
      PROXY_SERVER: ${{ secrets.PROXY_SERVER }}
      PROXY_PORT: ${{ secrets.PROXY_PORT }}
      PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
      PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}

      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASS: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir
          playwright install --with-deps

      - name: Run influencer lookup
        run: python srh.py

      - name: Git configuration
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Check for file changes
        id: git_diff
        run: |
          git add .
          if ! git diff --staged --quiet; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Commit & push if changed
        if: env.changed == 'true'
        run: |
          git commit -m "Auto: Updated ETL output"
          git push
